SCREEN_WIDTH = 800
SCREEN_HEIGHT = 800

BLOCK_SIZE = 30
NUM_ROWS = 20
NUM_COLUMNS = 8
INIT_SPEED = 500
ACCEL_RATE = 1.05

PLAY_WIDTH = BLOCK_SIZE * NUM_COLUMNS
PLAY_HEIGHT = BLOCK_SIZE * NUM_ROWS

ORIGIN = ((SCREEN_WIDTH - PLAY_WIDTH) // 2, min(SCREEN_HEIGHT-PLAY_HEIGHT, 80))

LEFT_KEY = 0
RIGHT_KEY = 1
ROTATE_KEY = 2
DOWN_KEY = 3
DROP_KEY = 4

REWARD = [0, 40, 100, 300, 1200]
